const express = require("express");
const router = express.Router();
const authRoutes = require("./authRoutes");
const userRoutes = require("./userRoutes");
const jobRoutes = require("./jobRoutes");
const savedJobsRoutes = require("./savedJobsRoutes");
const applicationRoutes = require("./applicationRoutes");
const analyticsRoutes = require("./analyticsRoutes");
const resumeRoutes = require("./resumeRoutes");
const uploadRoutes = require("./uploadRoutes");
const sessionRoutes = require("./sessionRoutes");
const questionRoutes = require("./questionRoutes");
router.use("/auth", authRoutes);
router.use("/user", userRoutes);
router.use("/jobs", jobRoutes);
router.use("/applications", applicationRoutes);
router.use("/saved-jobs", savedJobsRoutes);
router.use("/analytics", analyticsRoutes);
router.use("/resumes", resumeRoutes);
router.use("/sessions", sessionRoutes);
router.use("/questions", questionRoutes);
router.use("/upload", uploadRoutes);
module.exports = router;
