const express = require("express");
const router = express.Router();
const authRoutes = require("./authRoutes");
const userRoutes = require("./userRoutes");
const jobRoutes = require("./jobRoutes");
const applicationRoutes = require("./applicationRoutes");
const uploadRoutes = require("./uploadRoutes");
router.use("/auth", authRoutes);
router.use("/user", userRoutes);
router.use("/jobs", jobRoutes);
router.use("/applications", applicationRoutes);
router.use("/upload", uploadRoutes);
module.exports = router;
